language: php

php:
  - 5.4

before_script:
  - "mkdir -p ~/.composer"
  - composer self-update
  - composer install
  - npm install
  - ./node_modules/.bin/phantomjs --webdriver=8643
  
script:
  - bin/phpunit --coverage-text
